services:
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 4000
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lexiflow
      SPRING_DATASOURCE_USERNAME: lexiflow
      SPRING_DATASOURCE_PASSWORD: lexiflow
      JWT_SECRET: local-dev-secret-change-me-please-1234567890
    ports:
      - "4000:4000"
    networks:
      - lexiflow
    depends_on:
      - db

  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:4000/api/v1
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - lexiflow

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lexiflow
      POSTGRES_USER: lexiflow
      POSTGRES_PASSWORD: lexiflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lexiflow

networks:
  lexiflow:
    driver: bridge

volumes:
  pgdata:
